<?php
/**
 * @category    Inchoo
 * @package     Inchoo_KISSmetrics
 * @author      Branko Ajzele <ajzele@gmail.com>
 * @copyright   Copyright (c) Inchoo
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if ($identify = $this->getIdentify()):
   if(is_array($identify)){ ?>
        <script type="text/javascript">
            _kmq.push(['identify', '<?php echo $identify['id'] ?>']);
            _kmq.push(['set', {'Name':'<?php echo $identify['name'] ?>'}]);
            _kmq.push(['set', {'EMail':'<?php echo $identify['email'] ?>'}])
        </script>
    <?php }
endif;